In [1]:
import yaml
from google.cloud import bigquery

In [ ]:
config = yaml.load(open("credentials.yml"), yaml.Loader)
client = bigquery.Client.from_service_account_json(config["credentials_path"])

In [2]:
dataset_ref = bigquery.DatasetReference("bigquery-public-data", "google_analytics_sample")
table_ref = bigquery.TableReference(dataset_ref, "ga_sessions_20170801")
table = client.get_table(table_ref)

client.list_rows(table, max_results=5).to_dataframe()

,visitorId,visitNumber,visitId,visitStartTime,date,totals,trafficSource,device,geoNetwork,customDimensions,hits,fullVisitorId,userId,clientId,channelGrouping,socialEngagementType
0,<NA>,1,1501591568,1501591568,20170801,"{'visits': 1, 'hits': 1, 'pageviews': 1, 'time...","{'referralPath': None, 'campaign': '(not set)'...","{'browser': 'Chrome', 'browserVersion': 'not a...","{'continent': 'Europe', 'subContinent': 'South...",[],"[{'hitNumber': 1, 'time': 0, 'hour': 5, 'minut...",3418334011779872055,None,None,Organic Search,Not Socially Engaged
1,<NA>,2,1501589647,1501589647,20170801,"{'visits': 1, 'hits': 1, 'pageviews': 1, 'time...","{'referralPath': '/analytics/web/', 'campaign'...","{'browser': 'Chrome', 'browserVersion': 'not a...","{'continent': 'Asia', 'subContinent': 'Souther...","[{'index': 4, 'value': 'APAC'}]","[{'hitNumber': 1, 'time': 0, 'hour': 5, 'minut...",2474397855041322408,None,None,Referral,Not Socially Engaged
2,<NA>,1,1501616621,1501616621,20170801,"{'visits': 1, 'hits': 1, 'pageviews': 1, 'time...","{'referralPath': '/analytics/web/', 'campaign'...","{'browser': 'Chrome', 'browserVersion': 'not a...","{'continent': 'Europe', 'subContinent': 'North...","[{'index': 4, 'value': 'EMEA'}]","[{'hitNumber': 1, 'time': 0, 'hour': 12, 'minu...",5870462820713110108,None,None,Referral,Not Socially Engaged
3,<NA>,1,1501601200,1501601200,20170801,"{'visits': 1, 'hits': 1, 'pageviews': 1, 'time...","{'referralPath': '/analytics/web/', 'campaign'...","{'browser': 'Firefox', 'browserVersion': 'not ...","{'continent': 'Americas', 'subContinent': 'Nor...","[{'index': 4, 'value': 'North America'}]","[{'hitNumber': 1, 'time': 0, 'hour': 8, 'minut...",9397809171349480379,None,None,Referral,Not Socially Engaged
4,<NA>,1,1501615525,1501615525,20170801,"{'visits': 1, 'hits': 1, 'pageviews': 1, 'time...","{'referralPath': '/analytics/web/', 'campaign'...","{'browser': 'Chrome', 'browserVersion': 'not a...","{'continent': 'Americas', 'subContinent': 'Nor...","[{'index': 4, 'value': 'North America'}]","[{'hitNumber': 1, 'time': 0, 'hour': 12, 'minu...",6089902943184578335,None,None,Referral,Not Socially Engaged

In [8]:
table.schema[5]

SchemaField('totals', 'RECORD', 'NULLABLE', None, None, (SchemaField('visits', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('hits', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('pageviews', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('timeOnSite', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('bounces', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('transactions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('transactionRevenue', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('newVisits', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('screenviews', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('uniqueScreenviews', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('timeOnScreen', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('totalTransactionRevenue', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('sessionQualityDim', 'INTEGER', 'NULLABLE', None, None, (), None)), None)

In [9]:
table.schema[7]

SchemaField('device', 'RECORD', 'NULLABLE', None, None, (SchemaField('browser', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('browserVersion', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('browserSize', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('operatingSystem', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('operatingSystemVersion', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('isMobile', 'BOOLEAN', 'NULLABLE', None, None, (), None), SchemaField('mobileDeviceBranding', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('mobileDeviceModel', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('mobileInputSelector', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('mobileDeviceInfo', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('mobileDeviceMarketingName', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('flashVersion', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('javaEnabled', 'BOOLEAN', 'NULLABLE', None, None, (), None), SchemaField('language', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('screenColors', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('screenResolution', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('deviceCategory', 'STRING', 'NULLABLE', None, None, (), None)), None)

In [13]:
table.schema[10]

SchemaField('hits', 'RECORD', 'REPEATED', None, None, (SchemaField('hitNumber', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('time', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('hour', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('minute', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('isSecure', 'BOOLEAN', 'NULLABLE', None, None, (), None), SchemaField('isInteraction', 'BOOLEAN', 'NULLABLE', None, None, (), None), SchemaField('isEntrance', 'BOOLEAN', 'NULLABLE', None, None, (), None), SchemaField('isExit', 'BOOLEAN', 'NULLABLE', None, None, (), None), SchemaField('referer', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('page', 'RECORD', 'NULLABLE', None, None, (SchemaField('pagePath', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('hostname', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('pageTitle', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('searchKeyword', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('searchCategory', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('pagePathLevel1', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('pagePathLevel2', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('pagePathLevel3', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('pagePathLevel4', 'STRING', 'NULLABLE', None, None, (), None)), None), SchemaField('transaction', 'RECORD', 'NULLABLE', None, None, (SchemaField('transactionId', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('transactionRevenue', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('transactionTax', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('transactionShipping', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('affiliation', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('currencyCode', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('localTransactionRevenue', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('localTransactionTax', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('localTransactionShipping', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('transactionCoupon', 'STRING', 'NULLABLE', None, None, (), None)), None), SchemaField('item', 'RECORD', 'NULLABLE', None, None, (SchemaField('transactionId', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('productName', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('productCategory', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('productSku', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('itemQuantity', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('itemRevenue', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('currencyCode', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('localItemRevenue', 'INTEGER', 'NULLABLE', None, None, (), None)), None), SchemaField('contentInfo', 'RECORD', 'NULLABLE', None, None, (SchemaField('contentDescription', 'STRING', 'NULLABLE', None, None, (), None),), None), SchemaField('appInfo', 'RECORD', 'NULLABLE', None, None, (SchemaField('name', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('version', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('id', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('installerId', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('appInstallerId', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('appName', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('appVersion', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('appId', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('screenName', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('landingScreenName', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('exitScreenName', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('screenDepth', 'STRING', 'NULLABLE', None, None, (), None)), None), SchemaField('exceptionInfo', 'RECORD', 'NULLABLE', None, None, (SchemaField('description', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('isFatal', 'BOOLEAN', 'NULLABLE', None, None, (), None), SchemaField('exceptions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('fatalExceptions', 'INTEGER', 'NULLABLE', None, None, (), None)), None), SchemaField('eventInfo', 'RECORD', 'NULLABLE', None, None, (SchemaField('eventCategory', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('eventAction', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('eventLabel', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('eventValue', 'INTEGER', 'NULLABLE', None, None, (), None)), None), SchemaField('product', 'RECORD', 'REPEATED', None, None, (SchemaField('productSKU', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('v2ProductName', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('v2ProductCategory', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('productVariant', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('productBrand', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('productRevenue', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('localProductRevenue', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('productPrice', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('localProductPrice', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('productQuantity', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('productRefundAmount', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('localProductRefundAmount', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('isImpression', 'BOOLEAN', 'NULLABLE', None, None, (), None), SchemaField('isClick', 'BOOLEAN', 'NULLABLE', None, None, (), None), SchemaField('customDimensions', 'RECORD', 'REPEATED', None, None, (SchemaField('index', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('value', 'STRING', 'NULLABLE', None, None, (), None)), None), SchemaField('customMetrics', 'RECORD', 'REPEATED', None, None, (SchemaField('index', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('value', 'INTEGER', 'NULLABLE', None, None, (), None)), None), SchemaField('productListName', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('productListPosition', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('productCouponCode', 'STRING', 'NULLABLE', None, None, (), None)), None), SchemaField('promotion', 'RECORD', 'REPEATED', None, None, (SchemaField('promoId', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('promoName', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('promoCreative', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('promoPosition', 'STRING', 'NULLABLE', None, None, (), None)), None), SchemaField('promotionActionInfo', 'RECORD', 'NULLABLE', None, None, (SchemaField('promoIsView', 'BOOLEAN', 'NULLABLE', None, None, (), None), SchemaField('promoIsClick', 'BOOLEAN', 'NULLABLE', None, None, (), None)), None), SchemaField('refund', 'RECORD', 'NULLABLE', None, None, (SchemaField('refundAmount', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('localRefundAmount', 'INTEGER', 'NULLABLE', None, None, (), None)), None), SchemaField('eCommerceAction', 'RECORD', 'NULLABLE', None, None, (SchemaField('action_type', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('step', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('option', 'STRING', 'NULLABLE', None, None, (), None)), None), SchemaField('experiment', 'RECORD', 'REPEATED', None, None, (SchemaField('experimentId', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('experimentVariant', 'STRING', 'NULLABLE', None, None, (), None)), None), SchemaField('publisher', 'RECORD', 'NULLABLE', None, None, (SchemaField('dfpClicks', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpMatchedQueries', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpMeasurableImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpQueries', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpRevenueCpm', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpRevenueCpc', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpViewableImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpPagesViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpClicks', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpMatchedQueries', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpMeasurableImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpQueries', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpRevenueCpm', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpRevenueCpc', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpViewableImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpPagesViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpClicks', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpMatchedQueries', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpMeasurableImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpQueries', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpRevenueCpm', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpRevenueCpc', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpViewableImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpPagesViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxClicks', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxMatchedQueries', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxMeasurableImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxQueries', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxRevenue', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxViewableImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxPagesViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsUnitsViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsUnitsMatched', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('viewableAdsViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('measurableAdsViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsPagesViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsClicked', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsRevenue', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpAdGroup', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('dfpAdUnits', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('dfpNetworkId', 'STRING', 'NULLABLE', None, None, (), None)), None), SchemaField('customVariables', 'RECORD', 'REPEATED', None, None, (SchemaField('index', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('customVarName', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('customVarValue', 'STRING', 'NULLABLE', None, None, (), None)), None), SchemaField('customDimensions', 'RECORD', 'REPEATED', None, None, (SchemaField('index', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('value', 'STRING', 'NULLABLE', None, None, (), None)), None), SchemaField('customMetrics', 'RECORD', 'REPEATED', None, None, (SchemaField('index', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('value', 'INTEGER', 'NULLABLE', None, None, (), None)), None), SchemaField('type', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('social', 'RECORD', 'NULLABLE', None, None, (SchemaField('socialInteractionNetwork', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('socialInteractionAction', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('socialInteractions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('socialInteractionTarget', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('socialNetwork', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('uniqueSocialInteractions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('hasSocialSourceReferral', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('socialInteractionNetworkAction', 'STRING', 'NULLABLE', None, None, (), None)), None), SchemaField('latencyTracking', 'RECORD', 'NULLABLE', None, None, (SchemaField('pageLoadSample', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('pageLoadTime', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('pageDownloadTime', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('redirectionTime', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('speedMetricsSample', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('domainLookupTime', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('serverConnectionTime', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('serverResponseTime', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('domLatencyMetricsSample', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('domInteractiveTime', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('domContentLoadedTime', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('userTimingValue', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('userTimingSample', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('userTimingVariable', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('userTimingCategory', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('userTimingLabel', 'STRING', 'NULLABLE', None, None, (), None)), None), SchemaField('sourcePropertyInfo', 'RECORD', 'NULLABLE', None, None, (SchemaField('sourcePropertyDisplayName', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('sourcePropertyTrackingId', 'STRING', 'NULLABLE', None, None, (), None)), None), SchemaField('contentGroup', 'RECORD', 'NULLABLE', None, None, (SchemaField('contentGroup1', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('contentGroup2', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('contentGroup3', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('contentGroup4', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('contentGroup5', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('previousContentGroup1', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('previousContentGroup2', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('previousContentGroup3', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('previousContentGroup4', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('previousContentGroup5', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('contentGroupUniqueViews1', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('contentGroupUniqueViews2', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('contentGroupUniqueViews3', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('contentGroupUniqueViews4', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('contentGroupUniqueViews5', 'INTEGER', 'NULLABLE', None, None, (), None)), None), SchemaField('dataSource', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('publisher_infos', 'RECORD', 'REPEATED', None, None, (SchemaField('dfpClicks', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpMatchedQueries', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpMeasurableImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpQueries', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpRevenueCpm', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpRevenueCpc', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpViewableImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpPagesViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpClicks', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpMatchedQueries', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpMeasurableImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpQueries', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpRevenueCpm', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpRevenueCpc', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpViewableImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsenseBackfillDfpPagesViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpClicks', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpMatchedQueries', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpMeasurableImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpQueries', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpRevenueCpm', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpRevenueCpc', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpViewableImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxBackfillDfpPagesViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxClicks', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxMatchedQueries', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxMeasurableImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxQueries', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxRevenue', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxViewableImpressions', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adxPagesViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsUnitsViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsUnitsMatched', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('viewableAdsViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('measurableAdsViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsPagesViewed', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsClicked', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('adsRevenue', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('dfpAdGroup', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('dfpAdUnits', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('dfpNetworkId', 'STRING', 'NULLABLE', None, None, (), None)), None)), None)

In [12]:
# Query to count the number of transactions per browser

query = """
    SELECT device.browser AS device_browser,
           SUM(totals.transactions) AS total_transactions
    FROM `bigquery-public-data.google_analytics_sample.ga_sessions_20170801`
    GROUP BY device_browser
    ORDER BY total_transactions DESC    
"""

safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=10**10)  # 10 GB
query_results = client.query(query, job_config=safe_config).to_dataframe()
query_results

              device_browser  total_transactions
0                     Chrome                  41
1                     Safari                   3
2                    Firefox                   1
3                       Edge                <NA>
4                    Coc Coc                <NA>
5                      Opera                <NA>
6          Internet Explorer                <NA>
7            Android Browser                <NA>
8            Safari (in-app)                <NA>
9                 UC Browser                <NA>
10             Nokia Browser                <NA>
11           Android Webview                <NA>
12  Mozilla Compatible Agent                <NA>
13                Opera Mini                <NA>
14                 YaBrowser                <NA>

In [14]:
# Now we'll work with the "hits" column as an example of data that is both nested and repeated. Since:
# "hits" is a STRUCT (contains nested data) and is repeated,
# "hitNumber", "page", and "type" are all nested inside the "hits" column, and
# "pagePath" is nested inside the "page" field,
# we can query these fields with the following syntax:

# Query to determine most popular landing point on the website
query = """
    SELECT hits.page.pagePath AS path,
           COUNT(hits.page.pagePath) AS counts
    FROM `bigquery-public-data.google_analytics_sample.ga_sessions_20170801`,
    UNNEST(hits) AS hits
    WHERE hits.type = 'PAGE' AND hits.hitNumber = 1
    GROUP BY path
    ORDER BY counts DESC
"""

safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=10**10)  # 10 GB
query_results = client.query(query, job_config=safe_config).to_dataframe()
query_results

                                                  path  counts
0                                                /home    1257
1               /google+redesign/shop+by+brand/youtube     587
2          /google+redesign/apparel/mens/mens+t+shirts     117
3                                         /signin.html      78
4                                         /basket.html      35
..                                                 ...     ...
116  /google+redesign/apparel/women+s+t+shirt/googl...       1
117  /google+redesign/apparel/mens+tshirts/google+m...       1
118  /google+redesign/apparel/womens+tshirts/google...       1
119           /google+redesign/drinkware/mugs+and+cups       1
120  /google+redesign/bags/water+bottles+and+tumble...       1

[121 rows x 2 columns]

In [15]:
dataset_ref = bigquery.DatasetReference("bigquery-public-data", "github_repos")
table_ref = bigquery.TableReference(dataset_ref, "sample_commits")
table = client.get_table(table_ref)

client.list_rows(table, max_results=5).to_dataframe()

,commit,tree,parent,author,committer,subject,message,trailer,difference,difference_truncated,repo_name,encoding
0,afdba32e2a9ea729a9f9f280dbf6c718773c7ded,d77cca8a096e5320f3194d4a6ca1b4fef2dc9b99,[d65e55d4999b394e37ffe12543ecd2a17b7c44fc],"{'name': 'Jason Gunthorpe', 'email': 'a99b91d7...","{'name': 'Peter Huewe', 'email': '014f16385c5a...",tpm: Pull everything related to /dev/tpmX into...,tpm: Pull everything related to /dev/tpmX into...,"[{'key': 'Signed-off-by', 'value': 'Jason Gunt...","[{'old_mode': 33188, 'new_mode': 33188, 'old_p...",<NA>,torvalds/linux,None
1,eb846d9f147455e4e5e1863bfb5e31974bb69b7c,443efbb146c7824508be817923bab04c2185810e,[3af6b35261182ff185db1f0fd271254147e2663e],"{'name': 'Hannes Reinecke', 'email': 'b0d1e9e4...","{'name': 'Christoph Hellwig', 'email': '923f77...",scsi: rename SERVICE_ACTION_IN to SERVICE_ACTI...,scsi: rename SERVICE_ACTION_IN to SERVICE_ACTI...,"[{'key': 'Signed-off-by', 'value': 'Hannes Rei...","[{'old_mode': 33188, 'new_mode': 33188, 'old_p...",<NA>,torvalds/linux,None
2,f8798ccbefc0e4ef7438c080b7ba0410738c8cfa,9133440693c02314f1f6f95629b3594ce24ad0f8,[261e767628bb5971b9032439818237cc8511ea94],"{'name': 'Yong Zhang', 'email': '34add0fe16a1f...","{'name': 'Florian Tobias Schandinat', 'email':...",video: irq: Remove IRQF_DISABLED,video: irq: Remove IRQF_DISABLED\n\nSince comm...,"[{'key': 'Signed-off-by', 'value': 'Yong Zhang...","[{'old_mode': 33188, 'new_mode': 33188, 'old_p...",<NA>,torvalds/linux,None
3,b83ae6d421435c6204150300f1c25bfbd39cd62b,99c6b661ab7de05c2fd49aa62624d2d6bf8abc69,[de1414a654e66b81b5348dbc5259ecf2fb61655e],"{'name': 'Christoph Hellwig', 'email': '923f77...","{'name': 'Jens Axboe', 'email': 'cd8c6775e60d6...",fs: remove mapping->backing_dev_info,fs: remove mapping->backing_dev_info\n\nNow th...,"[{'key': 'Signed-off-by', 'value': 'Christoph ...","[{'old_mode': 33188, 'new_mode': 33188, 'old_p...",<NA>,torvalds/linux,None
4,aaabee8b7686dfe49f10289cb4b7a817b99e5dd9,7ccc6cf829a93d46daf484164a5466c91eca2efa,"[795e9364215dc98b1dea888ebae22383ecbbb92a, 2f2...","{'name': 'Luciano Coelho', 'email': 'd1ef58086...","{'name': 'Luciano Coelho', 'email': 'd1ef58086...",Merge branch 'wl12xx-next' into for-linville,Merge branch 'wl12xx-next' into for-linville\n...,"[{'key': 'Conflicts', 'value': '', 'email': No...","[{'old_mode': 33188, 'new_mode': 33188, 'old_p...",<NA>,torvalds/linux,None

In [16]:
table.schema

[SchemaField('commit', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('tree', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('parent', 'STRING', 'REPEATED', None, None, (), None),
 SchemaField('author', 'RECORD', 'NULLABLE', None, None, (SchemaField('name', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('email', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('time_sec', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('tz_offset', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('date', 'TIMESTAMP', 'NULLABLE', None, None, (), None)), None),
 SchemaField('committer', 'RECORD', 'NULLABLE', None, None, (SchemaField('name', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('email', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('time_sec', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('tz_offset', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('date', 'TIMESTAMP', 'NULLABLE', None, None, (), None)), None),
 SchemaField('subject', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('message', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('trailer', 'RECORD', 'REPEATED', None, None, (SchemaField('key', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('value', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('email', 'STRING', 'NULLABLE', None, None, (), None)), None),
 SchemaField('difference', 'RECORD', 'REPEATED', None, None, (SchemaField('old_mode', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('new_mode', 'INTEGER', 'NULLABLE', None, None, (), None), SchemaField('old_path', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('new_path', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('old_sha1', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('new_sha1', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('old_repo', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('new_repo', 'STRING', 'NULLABLE', None, None, (), None)), None),
 SchemaField('difference_truncated', 'BOOLEAN', 'NULLABLE', None, None, (), None),
 SchemaField('repo_name', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('encoding', 'STRING', 'NULLABLE', None, None, (), None)]

In [22]:
# Write a query to find the individuals with the most commits in this table in 2016.  Your query should return a table with two columns:
# - `committer_name` - contains the name of each individual with a commit (from 2016) in the table
# - `num_commits` - shows the number of commits the individual has in the table (from 2016)

query = """
    SELECT committer.name AS committer_name,
           COUNT(commit) AS num_commits
    FROM `bigquery-public-data.github_repos.sample_commits`
    WHERE EXTRACT(YEAR FROM committer.date) = 2016
    GROUP BY committer_name
    ORDER BY num_commits DESC
"""

safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=10**10)  # 10 GB
query_results = client.query(query, job_config=safe_config).to_dataframe()
query_results

            committer_name  num_commits
0       Greg Kroah-Hartman         3545
1          David S. Miller         3120
2    TensorFlower Gardener         2449
3           Linus Torvalds         2424
4          Benjamin Pasero         1127
..                     ...          ...
748     Dominique d'Argent            1
749         Calvin Freitas            1
750                   nick            1
751                   Ivan            1
752              bugsfan45            1

[753 rows x 2 columns]

In [26]:
dataset_ref = bigquery.DatasetReference("bigquery-public-data", "github_repos")
table_ref = bigquery.TableReference(dataset_ref, "languages")
table = client.get_table(table_ref)

client.list_rows(table, max_results=5).to_dataframe()

             repo_name                         language
0    lemi136/puntovent     [{'name': 'C', 'bytes': 80}]
1       taxigps/nctool   [{'name': 'C', 'bytes': 4461}]
2          ahy1/strbuf   [{'name': 'C', 'bytes': 5573}]
3  nleiten/mod_rpaf-ng  [{'name': 'C', 'bytes': 30330}]
4  kmcallister/alameda  [{'name': 'C', 'bytes': 17077}]

In [24]:
table.schema

[SchemaField('repo_name', 'STRING', 'NULLABLE', None, None, (), None),
 SchemaField('language', 'RECORD', 'REPEATED', None, None, (SchemaField('name', 'STRING', 'NULLABLE', None, None, (), None), SchemaField('bytes', 'INTEGER', 'NULLABLE', None, None, (), None)), None)]

In [30]:
# Write a query to leverage the information in the `languages` table to determine which programming languages
# appear in the most repositories.  The table returned by your query should have two columns:
# - `language_name` - the name of the programming language
# - `num_repos` - the number of repositories in the `languages` table that use the programming language

query = """
    SELECT l.name AS language_name,
           COUNT(repo_name) AS num_repos
    FROM `bigquery-public-data.github_repos.languages`,
    UNNEST(language) AS l
    GROUP BY language_name
    ORDER BY num_repos DESC
"""

safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=10**10)  # 10 GB
query_results = client.query(query, job_config=safe_config).to_dataframe()
query_results

       language_name  num_repos
0         JavaScript    1099966
1                CSS     807826
2               HTML     777433
3              Shell     640886
4             Python     550905
..               ...        ...
497              SVG          1
498             Mint          1
499  KiCad Schematic          1
500              Org          1
501            Vyper          1

[502 rows x 2 columns]

In [31]:
# For this question, you'll restrict your attention to the repository with name `'polyrabbit/polyglot'`.
# Write a query that returns a table with one row for each language in this repository.  The table should have two columns:
# - `name` - the name of the programming language
# - `bytes` - the total number of bytes of that programming language
# Sort the table by the `bytes` column so that programming languages that take up more space in the repo appear first.

query = """
    SELECT l.name AS name,
           l.bytes AS bytes
    FROM `bigquery-public-data.github_repos.languages`,
    UNNEST(language) AS l
    WHERE repo_name = 'polyrabbit/polyglot'
    ORDER BY bytes DESC
"""

safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=10**10)  # 10 GB
query_results = client.query(query, job_config=safe_config).to_dataframe()
query_results

                    name   bytes
0                  Lasso  834726
1                      C  819142
2                Mercury  709952
3            Objective-C  495392
4    Game Maker Language  298131
..                   ...     ...
211                   XC      82
212              Arduino      81
213               Nimrod      43
214           AutoHotkey      23
215                  Tea      20

[216 rows x 2 columns]